{% set name = "typedload" %}
{% set version = "2.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typedload-{{ version }}.tar.gz
  sha256: 0cd60fb9fb2119e00643bc302ece6700da3146d145a6c45a39e2ec8151d740b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - typedload
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ltworf.codeberg.page/typedload/
  summary: Load and dump data from json-like format into typed data structures
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://codeberg.org/ltworf/typedload

extra:
  recipe-maintainers:
    - HeavyTony2
